[package]
name          = "amq-protocol-codegen"
version       = "4.1.0" # remember to update html_root_url
edition       = "2018"
authors       = ["Marc-Antoine Perennou <%arc-Antoine@Perennou.com>"]
description   = "AMQP specifications - codegen"
repository    = "https://github.com/sozu-proxy/amq-protocol"
documentation = "https://docs.rs/amq-protocol-codegen"
keywords      = ["amqp","rabbitmq","protocol"]
categories    = ["api-bindings","network-programming"]
license       = "BSD-2-Clause"

[lib]
name = "amq_protocol_codegen"

[dependencies]
handlebars = "^3.0"
serde_json = "^1.0"

[dependencies.amq-protocol-types]
version = "=4.1.0"
path    = "../types"

[dependencies.serde]
version  = "^1.0"
features = ["derive"]

[badges]
travis-ci = { repository = "sozu-proxy/amq-protocol" }
appveyor  = { repository = "Keruspe/amq-protocol" }
